default_platform(:ios)

platform :ios do
  desc "Build App for testing"
  private_lane :build_for_testing do
    cocoapods
    scan(
      clean: true,
      build_for_testing: true,
      devices: ["iPhone 11"]
    )
  end

  desc "Run tests without building"
  private_lane :test do
    scan(
      skip_build: true,
      test_without_building: true,
      devices: ["iPhone 11"]
    )
  end

  desc "Build application and run all the tests"
  lane :build_and_test do
    build_for_testing
    test
  end
end
