default_platform(:ios)

application_name = "TFSChat"
repository_url = "https://github.com/bebnev/tfschat"
author_name = "Bebnev Anton"
icon_url = "https://acdn.tinkoff.ru/static/documents/80f3f5f9-eabc-4b45-9c5f-30c048a8a756.png"

platform :ios do
  desc "Build App for testing"
  private_lane :build_for_testing do
    cocoapods
    scan(
      clean: true,
      build_for_testing: true,
      derived_data_path: "DerivedData/",
      devices: ["iPhone 11"]
    )
  end

  desc "Run tests without building"
  private_lane :test do
    scan(
      skip_build: true,
      test_without_building: true,
      derived_data_path: "DerivedData/",
      devices: ["iPhone 11"]
    )
  end

  private_lane :discord_notification do  |params|
    message = params.fetch(:message, "")
    last_commit_hash = last_git_commit[:commit_hash]

    discord_notifier(
      webhook_url: ENV["DISCORD_WEB_HOOK"],
      title: application_name,
      description: message,
      thumbnail_url: icon_url,
      fields: [
        {
          name: "Author: ", 
          value: author_name,
          inline: true
        },
        {
          name: "Commit: ",
          value: repository_url + "/commit/" + last_commit_hash,
          inline: true
        }
      ]
    )
  end

  desc "Build application and run all the tests"
  lane :build_and_test do
    begin
      build_for_testing
      test
      discord_notification(
        message: "Build succeed"
      )
      puts "OK"
    rescue => exception
    puts "Error"
      discord_notification(
        message: "Build failed"
      )
    end
  end
end
